exports.BANKS = [
	{
		name: "First Bank Plc",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692397800/firstBank_xtotn6.png",
		header: [
			"S/N",
			"TransID",
			"Currency",
			"Value Date",
			"Trans. Remarks",
			"Narration",
			"AccountNo",
			"Tran Date",
			"Instrument",
			"Branch",
			"Debit",
			"Credit",
			"Balance",
		],
		validator: ["TransID", "Credit", "Value Date", "Balance"],
		color: "dodgerblue",
		ulocations: ["PortHacort", "Lagos"],
	},
	{
		name: "Guarantee Trust Bank",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692397860/GTBANK_i8dz8v.png",
		header: [
			"Trans Date",
			"Narrative",
			"Value Date",
			"Debit",
			"Credit",
			"Originating Branch",
			"Reference",
		],
		validator: ["Trans Date", "Credit", "Narrative"],
		color: "crimson",
		image: "",
		ulocations: ["Lagos"],
	},
	{
		name: "First City Monument Bank(FCMB)",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692014327/fcmb_vuyci5.png",
		header: [
			"SN",
			"Tran Date",
			"Value Date",
			"Reference",
			"Transaction Details",
			"Withdrawal",
			"Deposit",
			"Balance",
		],
		validator: ["Tran Date", "Deposit", "Transaction Details", "Balance"],
		color: "rgb(145, 49, 214)",
		ulocations: ["PortHacort", "Abuja"],
	},
	{
		name: "Zenith Bank",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692397944/ZenithBank_oobln5.png",
		header: [
			"Transaction Date",
			"Value Date",
			"Description",
			"Deposit",
			"Withdrawal",
			"Balance",
		],
		validator: ["Transaction Date", "Description", "Deposit"],
		color: "rgb(247, 51, 58)",
		ulocations: ["PortHacort"],
	},
	{
		name: "FIDELITY Bank",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692397727/FIDELITY_trcsyr.png",
		header: [
			"TRANSACTION DATE",
			"DESCRIPTION",
			"VALUE DATE",
			"DEPOSIT",
			"WITHDRAWAL",
			"BALANCE",
		],
		validator: ["TRANSACTION DATE", "DESCRIPTION", "DEPOSIT"],
		color: "rgb(77, 194, 71)",
		ulocations: ["Lagos"],
	},
	{
		name: "United Bank of Africa(UBA)",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692398235/UBA_ihiv4w.png",
		header: [
			"TransactionDate",
			"Transaction Narration",
			"Value Date",
			"Withdrawal",
			"Deposit",
			"Account Balance",
			"Cheque Number",
		],
		validator: ["Transaction Date", "Account Balance", "Deposit"],
		color: "rgb(205, 45, 17)",
		ulocations: ["Lagos"],
	},
	{
		name: "Eco Bank",
		logo: "https://res.cloudinary.com/onethought/image/upload/v1692398065/New-Ecobank-Logo_modfy4.png",
		header: [
			"Date",
			"Description",
			"Reference No",
			"Debit",
			"Credit",
			"Balance",
		],
		validator: ["Date", "Credit", "Reference No"],
		color: "rgb(10, 128, 178)",
		ulocations: ["Lagos"],
	},
];
