exports.BANKS = [
	{
		name: "First Bank Plc",
		logo: "",
		header: [
			"S/N",
			"TransID",
			"Currency",
			"Value Date",
			"Trans. Remarks",
			"Narration",
			"AccountNo",
			"Tran Date",
			"Instrument",
			"Branch",
			"Debit",
			"Credit",
			"Balance",
		],
		validator: ["TransID", "Credit", "Value Date", "Balance"],
	},
	{
		name: "Guarantee Trust Bank",
		logo: "",
		header: [],
		validator: ["Trans Date", "Credit", "Narrative"],
	},
	{
		name: "First City Monument Bank(FCMB)",
		logo: "",
		header: [
			"SN",
			"Tran Date",
			"Value Date",
			"Reference",
			"Transaction Details",
			"Withdrawal",
			"Deposit",
			"Balance",
		],
		validator: ["Tran Date", "Deposit", "Transaction Details", "Balance"],
	},
	{
		name: "Zenith Bank",
		logo: "",
		header: [
			"Transaction Date",
			"Value Date",
			"Description",
			"Deposit",
			"Withdrawal",
			"Balance",
		],
		validator: ["Transaction Date", "Description", "Deposit"],
	},
];
